# Docker Compose file for ELK stack

# Build with:
# docker-compose build elk

# Run with:
# docker-compose up

wp:
image: oskarhane/wordpress
links:
- syslog-ng:syslog-ng
ports:
- "80"
syslog-ng:
image: syslog-ng

elk:
  build: .
  ports:
    - "5514:5514"
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
    - "5000:5000"
